# Generated by Mentat

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_githubrun_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrun',
            name='version',
            field=models.CharField(default='', max_length=100, verbose_name='version'),
        ),
    ]
